"""create categories and products tables

Revision ID: 5bb6dc849bf2
Revises: 
Create Date: 2026-08-29 09:56:21.426781

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5bb6dc849bf2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    schema='cadutrack'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), server_default='1', nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("location IN ('fridge', 'freezer', 'pantry')", name='ck_products_location'),
    sa.CheckConstraint('quantity > 0', name='ck_products_quantity_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['cadutrack.categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    schema='cadutrack'
    )
    op.create_index(op.f('ix_cadutrack_products_expires_at'), 'products', ['expires_at'], unique=False, schema='cadutrack')
    # ### end Alembic commands ###

    # Keep products.updated_at accurate for every writer, not just the API.
    # A server_default only fires on INSERT, so without this trigger a row edited
    # through psql or a future import script would keep a stale timestamp.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION cadutrack.set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER products_set_updated_at
        BEFORE UPDATE ON cadutrack.products
        FOR EACH ROW
        EXECUTE FUNCTION cadutrack.set_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS products_set_updated_at ON cadutrack.products")
    op.execute("DROP FUNCTION IF EXISTS cadutrack.set_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cadutrack_products_expires_at'), table_name='products', schema='cadutrack')
    op.drop_table('products', schema='cadutrack')
    op.drop_table('categories', schema='cadutrack')
    # ### end Alembic commands ###
