"""add product icon

Revision ID: 62084b54b4cf
Revises: e1d82af7f2ea
Create Date: 2026-08-31 15:00:26.815276

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '62084b54b4cf'
down_revision: str | None = 'e1d82af7f2ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('icon', sa.String(length=16), server_default='🧺', nullable=False), schema='cadutrack')
    op.add_column('products', sa.Column('icon_source', sa.String(length=10), server_default='default', nullable=False), schema='cadutrack')
    op.create_check_constraint('ck_products_icon_source', 'products', "icon_source IN ('default', 'lookup', 'ai', 'manual')", schema='cadutrack')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_products_icon_source', 'products', schema='cadutrack', type_='check')
    op.drop_column('products', 'icon_source', schema='cadutrack')
    op.drop_column('products', 'icon', schema='cadutrack')
    # ### end Alembic commands ###
