"""add alert settings

Revision ID: e1d82af7f2ea
Revises: 5bb6dc849bf2
Create Date: 2026-08-30 18:20:27.704244

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e1d82af7f2ea'
down_revision: str | None = '5bb6dc849bf2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('alert_time', sa.String(length=5), nullable=False),
    sa.Column('days_ahead', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alert_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'", name='ck_alert_settings_time_format'),
    sa.CheckConstraint('days_ahead >= 1', name='ck_alert_settings_days_ahead'),
    sa.CheckConstraint('id = 1', name='ck_alert_settings_singleton'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_settings')),
    schema='cadutrack'
    )
    # ### end Alembic commands ###

    # Reuse the trigger function created for products, so this table's
    # updated_at is maintained the same way rather than being a column that
    # silently keeps its insert value for ever.
    op.execute(
        """
        CREATE TRIGGER alert_settings_set_updated_at
        BEFORE UPDATE ON cadutrack.alert_settings
        FOR EACH ROW
        EXECUTE FUNCTION cadutrack.set_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS alert_settings_set_updated_at ON cadutrack.alert_settings")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_settings', schema='cadutrack')
    # ### end Alembic commands ###
