"""add icon settings and name cache

Revision ID: ebde07d3dd73
Revises: 62084b54b4cf
Create Date: 2026-08-31 15:32:10.189772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ebde07d3dd73'
down_revision: str | None = '62084b54b4cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icon_name_cache',
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('normalized_name', name=op.f('pk_icon_name_cache')),
    schema='cadutrack'
    )
    op.create_table('icon_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_icon_settings_singleton'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icon_settings')),
    schema='cadutrack'
    )
    # ### end Alembic commands ###

    # Reuse the trigger function from the initial migration, the same way
    # alert_settings does — autogenerate has no way to see this, since a
    # trigger is not part of the ORM metadata it introspects.
    op.execute(
        """
        CREATE TRIGGER icon_settings_set_updated_at
        BEFORE UPDATE ON cadutrack.icon_settings
        FOR EACH ROW
        EXECUTE FUNCTION cadutrack.set_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS icon_settings_set_updated_at ON cadutrack.icon_settings")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icon_settings', schema='cadutrack')
    op.drop_table('icon_name_cache', schema='cadutrack')
    # ### end Alembic commands ###
